---

- name: Create ProxySQL config file
  template:
    dest: /etc/proxysql.cnf
    group: root
    mode: 0400
    owner: root
    src: proxysql.cnf.j2

- name: Ensure that ProxySQL is running
  service:
    enabled: "{{ proxysql_service_enabled_state | default('yes') }}"
    name: proxysql
    state: "{{ proxysql_service_state | default('started') }}"

- name: Wait for the ProxySQL admin interface
  wait_for:
    connect_timeout: 2
    port: 6032
    timeout: 60
  when: proxysql_service_enabled

- include_tasks: config/proxysql_backend_servers.yml

- include_tasks: config/proxysql_global_variables.yml

- include_tasks: config/proxysql_mysql_users.yml

- include_tasks: config/proxysql_proxysql_servers.yml

- include_tasks: config/proxysql_query_rules.yml

- include_tasks: config/proxysql_replication_hostgroups.yml
